Vagrant.configure("2") do |config|

  config.memory = 1024
  config.cpus =2 

  config.vm.define "alma8" do |alma8|
     alma8.vm.box = "generic/alma8"
     alma8.vm.network "private_network", ip: "192.168.33.11"
     alma8.vm.hostname = "alma8"
  end
  config.vm.define "centos" do |centos|
    centos.vm.box = "generic/centos8s"
    centos.vm.network "private_network", ip: "192.168.33.12"
    centos.vm.hostname = "centos"
    centos.vm.provision "shell", 
      inline: "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config && systemctl restart sshd" 
  end
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "generic/ubuntu1804"
    ubuntu.vm.network "private_network", ip: "192.168.33.13"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.provision "shell", 
      inline: "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config && systemctl restart sshd" 
  end
end